# Generated by Django 4.2.10 on 2024-02-23 20:15

import builds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0002_alter_buildstring_build_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=builds.models.generate_random_id,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("build_string", models.CharField(max_length=9000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="BuildString",
        ),
    ]
