# Generated by Django 4.2.10 on 2024-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0003_buildmodel_delete_buildstring"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildmodel",
            name="build_string",
        ),
        migrations.AddField(
            model_name="buildmodel",
            name="build",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
