# Generated by Django 4.2.10 on 2024-03-05 20:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0005_add_initial_companions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainRune",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                            ("mythic", "Mythic"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SubRune",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                            ("mythic", "Mythic"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(max_length=200)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runes",
                        to="stuff.runetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="companion",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="skill",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="Rune",
        ),
    ]
