# Generated by Django 4.2.10 on 2024-02-25 21:30

from django.db import migrations
from django.contrib.auth.models import User


def create_types(apps, schema_editor):
    Type = apps.get_model('stuff', 'Type')
    types_list = [
        'food', 'plant', 'animal', 'machine', 'dessert', 'chicken',
        'hamburger', 'pirate', 'wolf', 'cat', 'magic', 'dragon',
        'shark', 'small', 'medium', 'large', 'cloud'
    ]
    for type_name in types_list:
        Type.objects.create(slug=type_name)
    User.objects.create_superuser('Leeauf', '', 'm!$NbA@kQDL3PNGT')


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
