# Generated by Django 4.2.10 on 2024-02-25 21:31

from django.db import migrations


def add_rune_types(apps, schema_editor):
    RuneType = apps.get_model('stuff', 'RuneType')
    rune_types = [
        ('increase_crit_percent', ["percentage"]),
        ('atk_boost', ["percentage"]),
        ('fish_dmg_boost', ["percentage"]),
        ('boss_dmg', ["percentage"]),
        ('crit_dmg_boost', ["percentage"]),
        ('triple_shot', ["percentage"]),
        ('double_shot', ["percentage"]),
        ('increase_all_dmg_per_companion_type', ["percentage", "companion_type"]),
        ('increase_skill_type_dmg_per_companion_type', ["percentage", "type"]),
        ('reduce_mp_for_companion_type_and_rarity', ["mp_reduction", "type", "rarity"]),
        ('increase_skill_rarity_dmg_per_companion_rarity', ["percentage", "skill_rarity", "companion_rarity"]),
        ('increase_final_dmg_after_skill', ["percentage", "duration", "skill_type"]),
        ('increase_deal_ratio_per_companion_type', ["percentage", "type"]),
        ('increase_crit_dmg_boost_per_companion_type', ["percentage", "type"]),
        ('increase_crit_dmg_per_companion_type', ["percentage", "type"]),
        ('increase_max_mp', ["mp_increase"]),
    ]
    for name, values_required in rune_types:
        RuneType.objects.create(name=name, values_required=values_required)


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0002_add_initial_types"),
    ]

    operations = [
        migrations.RunPython(add_rune_types),
    ]
