# Generated by Django 4.2.10 on 2024-03-05 22:10

from django.db import migrations
from django.utils.text import slugify


def update_slugs(apps, schema_editor):
    Skill = apps.get_model('stuff', 'Skill')
    Companion = apps.get_model('stuff', 'Companion')
    for i in Companion.objects.all():
        if not i.slug:
            i.slug = slugify(i.name)
            i.save()
    for i in Skill.objects.all():
        if not i.slug:
            i.slug = slugify(i.name)
            i.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0007_add_initial_runes"),
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
