# Generated by Django 4.2.10 on 2024-03-07 14:49

from django.db import migrations


def create_subrunes(apps, schema_editor):
    SubRune = apps.get_model('stuff', 'SubRune')
    RuneType = apps.get_model('stuff', 'RuneType')
    subrune_data = [
        {"name": "Dragon Enhanced", "slug": "dragon-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Dragon companion equipped."},
        {"name": "Small Enhanced", "slug": "small-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Small companion equipped."},
        {"name": "Shark Enhanced", "slug": "shark-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Shark type skills by 20% per one Shark companion equipped."},
        {"name": "CRIT Chance", "slug": "crit-chance", "rarity": "uncommon", "description": "Increases CRIT Chance by 10%."},
        {"name": "Wolf Enhanced", "slug": "wolf-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Wolf type skills by 20% per one Wolf companion equipped."},
        {"name": "ATK", "slug": "atk", "rarity": "uncommon", "description": "ATK Boost + 50%"},
        {"name": "Medium Enhanced", "slug": "medium-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Medium companion equipped."},
        {"name": "Dessert Enhanced", "slug": "dessert-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Dessert type skills by 20% per one Dessert companion equipped."},
        {"name": "Fish Boost", "slug": "fish-boost", "rarity": "uncommon", "description": "Fish DMG Boost + 25%"},
        {"name": "Cloud Enhanced", "slug": "cloud-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Cloud companion equipped."},
        {"name": "Boss Attack", "slug": "boss-attack", "rarity": "uncommon", "description": "Boss DMG Increase + 10%"},
        {"name": "Chicken Enhanced", "slug": "chicken-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Chicken companion equipped."},
        {"name": "Animal Enhanced", "slug": "animal-enhanced", "rarity": "uncommon", "description": "Increases All DMG by 3% per one Animal companion equipped."},
        {"name": "Cat Enhanced", "slug": "cat-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Cat type skills by 20% per one Cat companion equipped."},
        {"name": "Machine Enhanced", "slug": "machine-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Machine type skills by 20% per one Machine companion equipped."},
        {"name": "CRIT DMG", "slug": "crit-dmg", "rarity": "uncommon", "description": "CRIT DMG Boost + 25%"},
        {"name": "Triple Shot", "slug": "triple-shot", "rarity": "uncommon", "description": "Increases Triple Shot by 5%."},
        {"name": "Large Enhanced", "slug": "large-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Large companion equipped."},
        {"name": "Magic Enhanced", "slug": "magic-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Magic type skills by 20% per one Magic companion equipped."},
        {"name": "Double Shot", "slug": "double-shot", "rarity": "uncommon", "description": "Increases Double Shot by 10%."},
        {"name": "Hamburger Enhanced", "slug": "hamburger-enhanced", "rarity": "uncommon", "description": "Increases DMG of all skills by 10% per one Hamburger companion equipped."},
        {"name": "Food Enhanced", "slug": "food-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Food type skills by 20% per one Food companion equipped."},
        {"name": "Plant Enhanced", "slug": "plant-enhanced", "rarity": "uncommon", "description": "Increases the Skill DMG of Plant type skills by 20% per one Plant companion equipped."},
        {"name": "Plant Enhanced", "slug": "plant-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Plant type skills by 40% per one Plant companion equipped."},
        {"name": "Triple Shot", "slug": "triple-shot", "rarity": "rare", "description": "Increases Triple Shot by 10%."},
        {"name": "Fish Boost", "slug": "fish-boost", "rarity": "rare", "description": "Fish DMG Boost + 50%"},
        {"name": "Boss Attack", "slug": "boss-attack", "rarity": "rare", "description": "Boss DMG Increase + 20%"},
        {"name": "Chicken Enhanced", "slug": "chicken-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Chicken companion equipped."},
        {"name": "Cat Enhanced", "slug": "cat-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Cat type skills by 40% per one Cat companion equipped."},
        {"name": "Animal Enhanced", "slug": "animal-enhanced", "rarity": "rare", "description": "Increases All DMG by 5% per one Animal companion equipped."},
        {"name": "Machine Enhanced", "slug": "machine-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Machine type skills by 40% per one Machine companion equipped."},
        {"name": "Plant MP Improved", "slug": "plant-mp-improved", "rarity": "rare", "description": "Reduces required MP for Plant of Rare grade by 1.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["1", "plant", "rare"]},
        {"name": "Dragon Enhanced", "slug": "dragon-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Dragon companion equipped."},
        {"name": "CRIT DMG", "slug": "crit-dmg", "rarity": "rare", "description": "CRIT DMG Boost + 50%"},
        {"name": "Small Enhanced", "slug": "small-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Small companion equipped."},
        {"name": "Cloud Enhanced", "slug": "cloud-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Cloud companion equipped."},
        {"name": "Dessert Enhanced", "slug": "dessert-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Dessert type skills by 40% per one Dessert companion equipped."},
        {"name": "ATK", "slug": "atk", "rarity": "rare", "description": "ATK Boost + 100%"},
        {"name": "Shark Enhanced", "slug": "shark-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Shark type skills by 40% per one Shark companion equipped."},
        {"name": "Double Shot", "slug": "double-shot", "rarity": "rare", "description": "Increases Double Shot by 20%."},
        {"name": "Wolf Enhanced", "slug": "wolf-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Wolf type skills by 40% per one Wolf companion equipped."},
        {"name": "CRIT Chance", "slug": "crit-chance", "rarity": "rare", "description": "Increases CRIT Chance by 20%."},
        {"name": "Hamburger Enhanced", "slug": "hamburger-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Hamburger companion equipped."},
        {"name": "Magic Enhanced", "slug": "magic-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Magic type skills by 40% per one Magic companion equipped."},
        {"name": "Large Enhanced", "slug": "large-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Large companion equipped."},
        {"name": "Medium Enhanced", "slug": "medium-enhanced", "rarity": "rare", "description": "Increases DMG of all skills by 20% per one Medium companion equipped."},
        {"name": "Food Enhanced", "slug": "food-enhanced", "rarity": "rare", "description": "Increases the Skill DMG of Food type skills by 40% per one Food companion equipped."},
        {"name": "Boss Attack", "slug": "boss-attack", "rarity": "epic", "description": "Boss DMG Increase + 40%."},
        {"name": "ATK", "slug": "atk", "rarity": "epic", "description": "ATK Boost + 200%."},
        {"name": "Animal Enhanced", "slug": "animal-enhanced", "rarity": "epic", "description": "Increases All DMG by 10% per one Animal companion equipped."},
        {"name": "Dragon Enhanced", "slug": "dragon-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Dragon companion equipped."},
        {"name": "Fish Boost", "slug": "fish-boost", "rarity": "epic", "description": "Fish DMG Boost + 100%."},
        {"name": "Plant MP Improved", "slug": "plant-mp-improved", "rarity": "epic", "description": "Reduces required MP for Plant of Epic grade by 1.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["1", "plant", "epic"]},
        {"name": "Triple Shot", "slug": "triple-shot", "rarity": "epic", "description": "Increases Triple Shot by 20%."},
        {"name": "Animal MP Improved", "slug": "animal-mp-improved", "rarity": "epic", "description": "Reduces required MP for Animal of Epic grade by 1.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["1", "animal", "epic"]},
        {"name": "Machine Enhanced", "slug": "machine-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Machine type skills by 80% per one Machine companion equipped."},
        {"name": "CRIT DMG", "slug": "crit-dmg", "rarity": "epic", "description": "CRIT DMG Boost + 100%."},
        {"name": "Cat Enhanced", "slug": "cat-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Cat type skills by 80% per one Cat companion equipped."},
        {"name": "Machine MP Improved", "slug": "machine-mp-improved", "rarity": "epic", "description": "Reduces required MP for Machine of Epic grade by 1.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["1", "machine", "epic"]},
        {"name": "Magic Enhanced", "slug": "magic-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Magic type skills by 80% per one Magic companion equipped."},
        {"name": "Dessert Enhanced", "slug": "dessert-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Dessert type skills by 80% per one Dessert companion equipped."},
        {"name": "Wolf Enhanced", "slug": "wolf-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Wolf type skills by 80% per one Wolf companion equipped."},
        {"name": "Small Enhanced", "slug": "small-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Small companion equipped."},
        {"name": "Shark Enhanced", "slug": "shark-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Shark type skills by 80% per one Shark companion equipped."},
        {"name": "Cloud Enhanced", "slug": "cloud-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Cloud companion equipped."},
        {"name": "Hamburger Enhanced", "slug": "hamburger-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Hamburger companion equipped."},
        {"name": "Large Enhanced", "slug": "large-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Large companion equipped."},
        {"name": "Food Enhanced", "slug": "food-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Food type skills by 80% per one Food companion equipped."},
        {"name": "Medium Enhanced", "slug": "medium-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Medium companion equipped."},
        {"name": "Cloud Enhanced 2", "slug": "cloud-enhanced-2", "rarity": "epic", "description": "Increases the Skill DMG of Cloud type skills by 80% per one Cloud companion equipped."},
        {"name": "Plant Enhanced", "slug": "plant-enhanced", "rarity": "epic", "description": "Increases the Skill DMG of Plant type skills by 80% per one Plant companion equipped."},
        {"name": "Chicken Enhanced", "slug": "chicken-enhanced", "rarity": "epic", "description": "Increases DMG of all skills by 40% per one Chicken companion equipped."},
        {"name": "Animal Enhanced", "slug": "animal-enhanced", "rarity": "legendary", "description": "Increases All DMG by 30% per one Animal companion equipped."},
        {"name": "Machine Enhanced", "slug": "machine-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Machine type skills by 160% per one Machine companion equipped."},
        {"name": "Hamburger Enhanced", "slug": "hamburger-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Hamburger companion equipped."},
        {"name": "Zero MP Hamburger", "slug": "zero-mp-hamburger", "rarity": "legendary", "description": "Nullifies Hamburger companion's MP.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["1000", "burger", "all"]},
        {"name": "Cloud Enhanced", "slug": "cloud-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Cloud companion equipped."},
        {"name": "Legendary Enhancement", "slug": "legendary-enhancement", "rarity": "legendary", "description": "Increases the Skill DMG of Legendary skills by 200% per one Legendary companion equipped."},
        {"name": "Shark Enhanced", "slug": "shark-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Shark type skills by 160% per one Shark companion equipped."},
        {"name": "Wolf MP Improved", "slug": "wolf-mp-improved", "rarity": "legendary", "description": "Reduces required MP for Wolf of Legendary grade by 2.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["2", "wolf", "legendary"]},
        {"name": "Wolf Enhanced", "slug": "wolf-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Wolf type skills by 160% per one Wolf companion equipped."},
        {"name": "Wolf Enhanced", "slug": "wolf-enhanced-2", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Wolf companion equipped."},
        {"name": "Machine MP Improved", "slug": "machine-mp-improved", "rarity": "legendary", "description": "Reduces required MP for Machine of Legendary grade by 2.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["2", "machine", "legendary"]},
        {"name": "Large Enhanced", "slug": "large-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Large companion equipped."},
        {"name": "Chicken Enhanced", "slug": "chicken-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Chicken companion equipped."},
        {"name": "Medium Enhanced", "slug": "medium-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Medium companion equipped."},
        {"name": "CRIT DMG", "slug": "crit-dmg", "rarity": "legendary", "description": "CRIT DMG Boost + 200%"},
        {"name": "Cat Skill Boost", "slug": "cat-skill-boost", "rarity": "legendary", "description": "Increases the deal ratio of Cat type skills by 150% per each Cat type skill equipped."},
        {"name": "Magic Enhanced", "slug": "magic-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Magic type skills by 160% per one Magic companion equipped."},
        {"name": "Dragon Enhanced", "slug": "dragon-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Dragon companion equipped."},
        {"name": "Boss Attack", "slug": "boss-attack", "rarity": "legendary", "description": "Boss DMG Increase + 80%"},
        {"name": "Plant Enhanced", "slug": "plant-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Plant type skills by 160% per one Plant companion equipped."},
        {"name": "Fish Boost", "slug": "fish-boost", "rarity": "legendary", "description": "Fish DMG Boost + 200%"},
        {"name": "Small Enhanced", "slug": "small-enhanced", "rarity": "legendary", "description": "Increases DMG of all skills by 80% per one Small companion equipped."},
        {"name": "Cat Boost", "slug": "cat-boost", "rarity": "legendary", "description": "Increases final DMG by 200% for 3s after casting a Cat type skill."},
        {"name": "Dessert Enhanced", "slug": "dessert-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Dessert type skills by 160% per one Dessert companion equipped."},
        {"name": "Cat CRIT Boost", "slug": "cat-crit-boost", "rarity": "legendary", "description": "Increases CRIT DMG Boost by 150% with each equipped Cat companion."},
        {"name": "Pirate Boost", "slug": "pirate-boost", "rarity": "legendary", "description": "Increases final DMG by 200% for 3s after casting a Pirate type skill."},
        {"name": "Pirate Skill Boost", "slug": "pirate-skill-boost", "rarity": "legendary", "description": "Increases the deal ratio of Pirate type skills by 200% per each Pirate type skill equipped."},
        {"name": "Pirate CRIT Boost", "slug": "pirate-crit-boost", "rarity": "legendary", "description": "Increases CRIT DMG Boost by 150% with each equipped Pirate companion."},
        {"name": "Pirate CRIT Enhanced", "slug": "pirate-crit-enhanced", "rarity": "legendary", "description": "Increases CRIT DMG dealt by 150% with each equipped Pirate companion."},
        {"name": "Animal MP Improved", "slug": "animal-mp-improved", "rarity": "legendary", "description": "Reduces required MP for Animal of Legendary grade by 2.", "type": "reduce_mp_for_companion_type_and_rarity", "values": ["2", "animal", "legendary"]},
        {"name": "Food Enhanced", "slug": "food-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Food type skills by 160% per one Food companion equipped."},
        {"name": "Cat Enhanced", "slug": "cat-enhanced", "rarity": "legendary", "description": "Increases the Skill DMG of Cat type skills by 160% per one Cat companion equipped."},
        {"name": "Max MP Increased", "slug": "max-mp-increased", "rarity": "legendary", "description": "Increases the maximum MP by 4.", "type": "increase_max_mp", "values": ["4"]},
        {"name": "Pirate CRIT Enhanced", "slug": "pirate-crit-enhanced", "rarity": "mythic", "description": "Increases CRIT DMG dealt by 1,500% with each equipped Pirate companion."},
        {"name": "Pirate CRIT Boost", "slug": "pirate-crit-boost", "rarity": "mythic", "description": "Increases CRIT DMG Boost by 1,500% with each equipped Pirate companion."},
        {"name": "Pirate Boost", "slug": "pirate-boost", "rarity": "mythic", "description": "Increases final DMG by 5,000% for 3s after casting a Pirate type skill."},
        {"name": "Cat CRIT Boost", "slug": "cat-crit-boost", "rarity": "mythic", "description": "Increases CRIT DMG Boost by 1,500% with each equipped Cat companion."},
        {"name": "Cat Boost", "slug": "cat-boost", "rarity": "mythic", "description": "Increases final DMG by 5,000% for 3s after casting a Cat type skill."},
        {"name": "Wolf CRIT Enhanced", "slug": "wolf-crit-enhanced", "rarity": "mythic", "description": "Increases CRIT DMG dealt by 1,500% with each equipped Wolf companion."}
    ]

    for subrune in subrune_data:
        rune = SubRune.objects.create(name=subrune["name"], slug=subrune['slug'], rarity=subrune['rarity'], description=subrune['description'], values=subrune['values'] if 'values' in subrune.keys() else [])
        if "type" in subrune.keys():
            rune_type = RuneType.objects.get(name=subrune["type"])
            rune.type = rune_type
            rune.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0008_update_slugs"),
    ]

    operations = [
        migrations.RunPython(create_subrunes),
    ]
