# Generated by Django 4.2.10 on 2024-03-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0009_update_2-5-0"),
    ]

    operations = [
        migrations.AddField(
            model_name="companion",
            name="affected_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stuff.skill",
            ),
        ),
        migrations.AddField(
            model_name="companion",
            name="cooldown_per_level",
            field=models.JSONField(default=dict),
        ),
    ]
