# Generated by Django 4.2.10 on 2024-04-11 08:42

from django.db import migrations


def update(apps, schema_editor):
    Companion = apps.get_model('stuff', 'Companion')
    Skill = apps.get_model('stuff', 'Skill')
    MainRune = apps.get_model('stuff', 'MainRune')
    SubRune = apps.get_model('stuff', 'SubRune')
    RuneType = apps.get_model('stuff', 'RuneType')
    Type = apps.get_model('stuff', 'Type')

    food_type, _ = Type.objects.get_or_create(slug='food')
    large_type, _ = Type.objects.get_or_create(slug='large')
    small_type, _ = Type.objects.get_or_create(slug='small')

    chef_hot_dog, _ = Companion.objects.get_or_create(
        name="Chef Hot-Dog",
        slug='chef-hot-dog',
        rarity="legendary",
        base_mp=8,
    )
    chef_hot_dog.types.add(large_type, food_type)
    chef_hot_dog.save()

    frozen_berry, _ = Companion.objects.get_or_create(
        name="Frozen Berry",
        slug='frozen-berry',
        rarity="legendary",
        base_mp=8,
    )
    frozen_berry.types.add(small_type, food_type)
    frozen_berry.save()

    hot_dog_batter_skill, _ = Skill.objects.get_or_create(
        name='Hot Dog Batter',
        slug='hot-dog-batter',
        rarity='legendary',
        description='Summons giant hot dog battering the enemies. The Skill lasts for 5s attacking enemies 3 times per second. Each attack deals 1200% damage',
        cooldown=75.0,
    )
    hot_dog_batter_skill.types.add(food_type)
    hot_dog_batter_skill.save()

    party_time_skill, _ = Skill.objects.get_or_create(
        name='Party Time',
        slug='party-time',
        rarity='legendary',
        description='Increases the skill DMG of all Food skills for 10s by 1000%. Let the party begin!',
        cooldown=75.0,
    )
    party_time_skill.types.add(food_type)
    party_time_skill.save()

    MainRune.objects.create(
        name="Hot Dog Terror",
        slug="hot-dog-terror",
        rarity="legendary",
        description="Grants the terror effect at a 100% chance when Hot Dog Batter hits the target, increasing DMG dealt to the enemy by 500% for 5s.",
    )

    MainRune.objects.create(
        name="Party Time Enhanced",
        slug="party-time-enhanced",
        rarity="legendary",
        description="Enhances Party Time increasing the skill duration by 5 seconds and the effect of Party Time by 500%.",
    )

    food_mp = SubRune.objects.create(
        name="Food MP Improved",
        slug="food-mp-improved",
        rarity="legendary",
        description="Reduces required MP for Food type companions of legendary grade by 2",
        values=["2", "food", "legendary"]
    )
    rune_type = RuneType.objects.get(name="reduce_mp_for_companion_type_and_rarity")
    food_mp.type = rune_type
    food_mp.save()

    SubRune.objects.create(
        name="Food CRIT Enhanced",
        slug="food-crit-enhanced",
        rarity="mythic",
        description="Increases CRIT DMG dealt by 1500% with each equipped Food companion.",
    )

    SubRune.objects.create(
        name="Food Enhanced 2",
        slug="food-enhanced-2",
        rarity="legendary",
        description="Increases DMG of all skills by 80% per one Food companion equipped.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0011_add_skill_cd_to_companions"),
    ]
    operations = [
        migrations.RunPython(update),
    ]
