# Generated by Django 4.2.10 on 2024-09-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0012_update_2-8-0"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companion",
            name="cooldown_per_level",
        ),
    ]
