# Generated by Django 5.0.9 on 2024-09-12 14:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuff", "0013_remove_companion_cooldown_per_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrune",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runes",
                to="stuff.runetype",
            ),
        ),
        migrations.AlterField(
            model_name="subrune",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
