# Generated by Django 5.0.9 on 2025-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_companion_mp_reduc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('supreme', 'Supreme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mainrune',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='mainrune',
            name='rarity',
            field=models.CharField(choices=[('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('supreme', 'Supreme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('supreme', 'Supreme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subrune',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='subrune',
            name='rarity',
            field=models.CharField(choices=[('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('supreme', 'Supreme')], max_length=10),
        ),
    ]
