# Generated by Django 4.2.10 on 2024-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeTrade",
            fields=[
                (
                    "exchange_uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("listing_time", models.DateTimeField()),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("shoes", "Shoes"),
                            ("gloves", "Gloves"),
                            ("hat", "Hat"),
                            ("scarf", "Scarf"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gear_type",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("exchange_left", models.IntegerField(default=0)),
                ("durability", models.IntegerField(default=0)),
            ],
        ),
    ]
