# Generated by Django 4.2.10 on 2024-06-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_alter_exchangetrade_gear_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangetrade",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
